---
title: "coasting"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: flatly
---

```{r setup, include=FALSE}
libs <- c("flexdashboard","DT","tidyverse","plotly","leaflet","leaflet.extras","DBI","lubridate","mapdata","stravR")
purrr::walk(libs, ~library(.,character.only = T))

# clear the memory
rm(list=ls(all = TRUE))

source("config.R")
source("R/load.R")

coastal_data <- load_coastal_data(export_rider_traces = TRUE)

full_dataset <- coastal_data$full_dataset
rides_index <- coastal_data$rides_index
position_extremities <- coastal_data$position_extremities
image_metadata <- coastal_data$image_metadata
riders <- coastal_data$riders
ferries <- coastal_data$ferries

latest_adventure <- get_latest_adventure(rides_index)
latest_adventure_photos <- filter_adventure_images(image_metadata, latest_adventure)
latest_adventure_summary <- summarise_adventure(
  latest_adventure,
  latest_adventure_photos
)
longest_day_activity <- get_longest_day_activity(rides_index)
biggest_climb_activity <- get_biggest_climb_activity(rides_index)

```

Maps
===================================== 

Row {data-height=120}
-----------------------------------------------------------------------

### Miles ridden

```{r}
valueBox(rides_index$distance_miles %>% sum() %>% floor(), icon = "fa-bicycle", color = "#EDF0F1")
```

### Metres climbed

```{r}
valueBox(rides_index$elevation_metres %>% sum() %>% floor(), icon = "fa-arrow-up", color = "#EDF0F1")
```

### Days ridden

```{r}
valueBox(rides_index$start_date %>% unique() %>% length(), icon = "fa-sun", color = "#EDF0F1")
```

### Ferries taken

```{r}
valueBox(nrow(ferries), icon = "fa-ship", color = "#EDF0F1")

```

Row {data-height=650}
-----------------------------------------------------------------------

### Overall progress

```{r}
draw_map("all", full_dataset, rides_index, image_metadata)
```

### Latest ride

```{r}
draw_map("latest", full_dataset, rides_index, image_metadata)
```

Row {data-height=120}
-----------------------------------------------------------------------

### Most Northerly

```{r}
get_coord_valuebox("N", position_extremities)
```

### Most Southerly

```{r}
get_coord_valuebox("S", position_extremities)
```

### Most Easterly

```{r}
get_coord_valuebox("E", position_extremities)
```

### Most Westerly

```{r}
get_coord_valuebox("W", position_extremities)
```

Latest Adventure
=====================================

Row {data-height=120}
-----------------------------------------------------------------------

### `r latest_adventure_summary$title`

```{r}
valueBox(
  latest_adventure_summary$date_range,
  icon = "fa-calendar",
  color = "#EDF0F1"
)
```

### Coastal miles

```{r}
valueBox(
  floor(latest_adventure_summary$distance_miles),
  icon = "fa-bicycle",
  color = "#EDF0F1"
)
```

### Metres climbed

```{r}
valueBox(
  floor(latest_adventure_summary$elevation_metres),
  icon = "fa-arrow-up",
  color = "#EDF0F1"
)
```

### Moving time

```{r}
valueBox(
  format_duration_hours(latest_adventure_summary$moving_seconds),
  icon = "fa-clock",
  color = "#EDF0F1"
)
```

Row {data-height=650}
-----------------------------------------------------------------------

### Latest adventure map

```{r}
draw_map("latest", full_dataset, rides_index, image_metadata)
```

### Days

```{r}
latest_adventure_days <- format_adventure_day_table(latest_adventure)

datatable(
  latest_adventure_days,
  escape = FALSE,
  colnames = c(
    "Date",
    "Ride",
    "Riders",
    "Total Distance (mi)",
    "Coastal Distance (mi)",
    "Elevation (m)",
    "Moving Time",
    "Percentage Coastal"
  ),
  rownames = FALSE,
  options = list(
    dom = "t",
    pageLength = nrow(latest_adventure_days)
  )
) %>%
  formatRound(
    c("distance_whole_ride_miles", "distance_miles", "elevation_metres"),
    digits = 1
  ) %>%
  formatPercentage("coastal_percentage", digits = 1)
```

Row {data-height=360}
-----------------------------------------------------------------------

### Photos

```{r}
render_adventure_photo_gallery(latest_adventure_photos)
```

Stats
===================================== 

Row {data-height=420}
-----------------------------------------------------------------------

### Cumulative coastal miles

```{r}
draw_cumulative_progress_plot(rides_index)
```

### Distance / climb by year

```{r}
draw_miles_climb_plot(rides_index)
```

Row {data-height=430}
-----------------------------------------------------------------------

### Contributors

```{r}
draw_rider_contribution_plot(rides_index)
```

### Seasonality

```{r}
draw_monthly_activity_plot(rides_index)
```

### Miles ridden by hour of day

```{r}
draw_miles_by_hour_plot(full_dataset)
```

Rides
===================================== 

Row {data-height=120}
-----------------------------------------------------------------------

### Adventures

```{r}
valueBox(
  n_distinct(rides_index$adventure_id),
  icon = "fa-map",
  color = "#EDF0F1"
)
```

### Active years

```{r}
valueBox(
  n_distinct(rides_index$yr),
  icon = "fa-calendar",
  color = "#EDF0F1"
)
```

### Longest coastal day

```{r}
valueBox(
  str_glue("{floor(longest_day_activity$distance_miles)} mi"),
  icon = "fa-road",
  color = "#EDF0F1",
  href = longest_day_activity$strava_link
)
```

### Biggest climb day

```{r}
valueBox(
  str_glue(
    "{format(floor(biggest_climb_activity$elevation_metres), big.mark = ',')} m"
  ),
  icon = "fa-arrow-up",
  color = "#EDF0F1",
  href = biggest_climb_activity$strava_link
)
```

Row {.tabset data-height=650}
-----------------------------------------------------------------------

### Rider leaderboard

```{r}
rider_leaderboard <- format_rider_leaderboard(rides_index)

datatable(
  rider_leaderboard,
  rownames = FALSE,
  colnames = c(
    "Rider",
    "Adventures",
    "Ride Days",
    "Coastal Miles",
    "Elevation (m)",
    "Longest Day (mi)",
    "Biggest Climb (m)"
  ),
  options = list(
    dom = "t",
    pageLength = nrow(rider_leaderboard)
  )
) %>%
  formatRound(
    c(
      "coastal_miles",
      "elevation_metres",
      "longest_day_miles",
      "biggest_climb_metres"
    ),
    digits = 1
  )
```

### Adventure rankings

```{r}
adventure_rankings <- format_adventure_rankings(rides_index)

datatable(
  adventure_rankings,
  rownames = FALSE,
  colnames = c(
    "Adventure",
    "Start Date",
    "End Date",
    "Days",
    "Activities",
    "Coastal Miles",
    "Elevation (m)",
    "Riders"
  ),
  options = list(
    dom = "t",
    pageLength = nrow(adventure_rankings)
  )
) %>%
  formatRound(c("coastal_miles", "elevation_metres"), digits = 1)
```

### Hardest coastal days

```{r}
hardest_days <- format_hardest_days_table(rides_index)

datatable(
  hardest_days,
  escape = FALSE,
  rownames = FALSE,
  colnames = c(
    "Date",
    "Ride",
    "Riders",
    "Coastal Miles",
    "Elevation (m)",
    "Metres / Mile",
    "Moving Seconds",
    "Moving Time"
  ),
  options = list(
    dom = "t",
    pageLength = nrow(hardest_days),
    columnDefs = list(
      list(visible = FALSE, targets = 6),
      list(orderData = 6, targets = 7)
    )
  )
) %>%
  formatRound(
    c("distance_miles", "elevation_metres", "climb_per_mile"),
    digits = 1
  )
```

### All rides

```{r}
dt <- rides_index %>% 
  mutate(ride_name_link = str_c("<a href = \"",strava_link,"\">",ride_name,"</a>"),
         ride_start_lbl = as_date(start_date_local),
         riders_display = map_chr(riders, format_rider_list),
         distance_miles = if_else(distance_miles > distance_whole_ride_miles, distance_whole_ride_miles, distance_miles)) %>%
  select(ride_name_link, ride_start_lbl, riders_display, distance_whole_ride_miles, distance_miles, elevation_metres, coastal_percentage)

datatable(dt,
          escape = FALSE,
          colnames =  c("Ride Name", "Ride Date", "Riders", "Total Distance (mi)", "Coastal Distance (mi)", "Elevation (m)", "Percentage Coastal"), 
          rownames = FALSE,
          extensions = 'Scroller', #'Buttons',
          options = list(dom = 'Bfrti',
                         scrollY = 350,
                         pageLength = nrow(rides_index),
                         searchHighlight = TRUE)) %>% 
  formatRound(c("distance_whole_ride_miles", "distance_miles", "elevation_metres"), digits = 1) %>% 
  formatPercentage("coastal_percentage", digits = 1)
```
