```{r setup, include=FALSE}
source(here::here("R", "load.R"))
load_coastal_packages()
con <- connect_coastal_database()

rides <- load_coastal_data(con)$rides_index

rides <- rides |> mutate(details = str_glue("{ride_name} | {as_date(start_date_local)} | {str_replace_all(riders, '[|]', ', ')} | {strava_link}"))

```

# Notes

How long is the coastline anyway? Section on how the route planning was done, the selective re-riding of sections, coastal paradox / fractal geometry etc 
Section on logistics - bike setups, gear carried, how we got to / from sections (night trains etc). Including when it messed up (cancelled night train, unexpected overnight stay in Carlisle, Schalk smashing himself up).

## `r rides$details[rides$activity_id == 753905298]`

Ride that started it all. Part of “De Ronde van Anglia”. Nick and Mandy joined as far as Happisburgh. Big curry the night before. New Mason Definition got it all started. Dumpy had lots of punctures, had some dodgy rim tape on his front wheel.

## `r rides$details[rides$activity_id == 1250104735]`

First big ride that started to add some momentum to the coastal project - meant we were actually “doing it”. Lobster at the Lobster Shack in Whitstable. Schalk trying to pee from the bike on the sea wall as I pushed him along (he failed). Nice pint in Deal. Lovely view approaching Dover seeing the ferries crossing from France. Then seeing the sun dip behind Dover castle. 

## `r rides$details[rides$activity_id == 1250873973]`

Absolutely FREEZING when we left, but a gorgeous morning. Camber Sands, Jury’s Gap, Birling Gap all stunning. Needing to seriously kit up once the sun dipped (Brighton way). Back to London the day after (though not Coastal obviously)

## `r rides$details[rides$activity_id == 18241293474]`

Started the day with train to Grantham, rode to Gosberton for tea and teacakes at TS’s dad’s place. Then to Boston to meet the coast. Rode gravel down the banks of The Haven, all the way to where it meets the wash, then along the sea bank. Back on tarmac and then stopped for lunch where that guy attempted the ultimate breakfast challenge before throwing outside. From there all the way up the coast path until we got to Mablethorpe.

## `r rides$details[rides$activity_id == 18255965742]`

Big day out round the Humber estuary with a lot of gravel. Nice gravel stretch up to Cleethorpes, and then again once we were level with Hull, with a great view of the Humber Bridge as we followed the river’s edge. Then riverside again (now in Yorkshire) as we made our way through Hull and across the flatlands down to Spurn Point. Very exposed to the wind. Then up the coast to Withernsea for the night.

## `r rides$details[rides$activity_id == 18264839802]`

Only a short coastal section at the start of the day with some gravel thrown in. Then turned inland to York for the train back to London. 

## `r rides$details[rides$activity_id == 4055608848]`

Flamborough Headlands spectacular. Scarborough for amazing fish and chips by the dock. Then up on to the moors as the elevation became a lot more challenging. Descend down to Robin Hood’s bay, couple of pints then ride back up (30%!!) and nearly spray the pints over the handlebars. Have to zig zag across the road to get up (carrying kit). Descending into Whitby as the sun was setting. Stayed at some cabins in Staithes and walked into the village for a lovely seafood dinner at the Cod and Lobster. The local cat at the cabins came into our room for the night - we left the door open because three guys riding all day kick out some serious heat in a small cabin (was a two bed room, with Schalky on a little camp bed).

## `r rides$details[rides$activity_id == 4058882682]`

Wonderfully clear day leaving Staithes. Middlesborough TOTAL shit hole. Had to go in to town because the transporter bridge was out of service. Hartlepool with all the old oil / gas rigs by the waterside. Tunnel under the Tyne to get into Newcastle. Train back to London.

## `r rides$details[rides$activity_id == 5560406484]`

First miles on the west side of the country. Night train to Penzance. Need to cover the night train experience at some point, including riding through London, Brixton meet for beers, James Brown’s “Night Train” on the UE Boom. This night train was a disaster because it actually started at Reading and we had to jump on a normal train - with bikes - to get there. Came out of Penzance station, fired up the Garmin, so many climbs on the Garmin (27? Need to find out). Started off riding down the beach because the footpath was closed for repairs. St Michael’s Mount (sailing connection). Then rode to the Lizard which was beautiful - amazingly clear day. Old lifeboat slipway below us.
Then the day got progressively tougher. Constant descending into beautiful fishing village and then very tough climb to get out. Started to wear after a while, definitely weren’t eating or drinking enough. Just after Portholland we went on a narrow track and Darren missed the trail, and dropped down into some bushes (get picture from Poes).
Got the ferry from Fowey to Polruan, begged them to make three more meals (no seats inside, about to stop serving from the hatch). Then climbed out of the village and Schalk had his mega bonk - hallucinating, getting off the bike and randomly fiddling with bags. Darren and I sat him down, dug out all the food we had (1 gel and a few chocolates we scooped up on the night train), and pumped it into him.
Got him going just about. Rode into Polperro on fumes looking for something to eat. It was late and options were very thin but Nelson’s restaurant - absolute legends - who were fully booked at least did us three pints of coke to get some fuel in. Slightly fortified we pushed on to Looe. As we descended into town we saw a BP garage - its green lights so incredibly welcome - and dived in there. Cue some terrible diet plans (chocolate, haribo, crisps) and struggled on to our accommodation for the night. A wooden pod in a field. We got there very late (about 2230) absolutely broken. The only shower was a hanging bag outside (absolute lols). We crashed out - beds so welcome - and when we woke up it was gorgeous. We’d arrived in the dark so had no idea we were in a field surrounded by animals.

## `r rides$details[rides$activity_id == 5564763338]`

Got up and pushed on to Plymouth for our breakfast. Got the chain ferry across the Tamer. Tidal road at Aveton Gifford, tide was flooding so we only just made it over. Didn’t get to the Starcross - Exmouth Ferry in time so had to ride up and around the estuary instead.

## `r rides$details[rides$activity_id == 5575822827]`

Exmouth massive fry up on the way out. Rainy and very misty - picture of the chaps coming out of the mist. Darren’s crash crossing the ford at Sidmouth.
Climb up from Lulworth to Whitewalls Viewpoint (near abandoned Tyneham village) as the weather had improved with the sun out.
England match at the Euros (look up the details). Corfe Castle was beautiful. Roads super quiet once the match had started.
Rode on to chain ferry across to Sandbanks. Then pushed on along the beach path into Bournemouth. Next day on to London (but not Coastal).

## `r rides$details[rides$activity_id == 5824943588]`

Night train again. Met Tom in Penzance - he went night before and got pissed up on his own. Wyndy’s debut. Straight to Land’s end for photos. Stretch from St Just to St Ives one of the most beautiful of the whole coastal adventure. Cornish pasties in Hayle. Then the infamous night at Dolphins Hostel in Tintagel. 

## `r rides$details[rides$activity_id == 5831004889]`

A truly epic day. 125 miles, rain, 3800m elevation. Incredible scenery - black sands at Millook. Tough going all day - sheltering outside that pub in the rain that wouldn’t let us in with a Peacock cruising around outside. Then descending down into Lynmouth in the pissing rain, super steep and sketchy. Fish and chips and begging phone call to the Washford Inn asking them to help us out with food, said they’d cook and heat up if we were late. Then the stunning climb out of Lynmouth as the weather cleared.
Nightfall on the moors, terrified of hitting a sheep at speed, Wyndy without a proper front light. Made it to the Washford Inn at 2136. Neil Diamond tribute act in full swing. Sat straight down in manky kit, dinner arrived, loads of beers, dancing to sweet Caroline. Crazy night.

## `r rides$details[rides$activity_id == 5836688186]`

Hangovers all round, Tom Skipp turns on the pace and rips us all to bits. Some food in Weston-Super-Mare. Triumphant arrival across the Clifton Suspension bridge. Then more beers. SB and me rode all the way back to London next day.

## `r rides$details[rides$activity_id == 5906287061]`

Big day out on the marshes. Visiting both of the London Stones. Wakering Stairs in the misty haze that morning. Then MOD Shoeburyness. A lap of Canvey Island, followed by a long wait at Tilbury for a ferry to Gravesend. Forgot to refill our bottles at the pub lunch stop and headed onto the Hoo Peninsula with nearly empty water bottles and no shops for miles - serious schoolboy error. The marshes beautiful in their isolation; just us and some cattle. Saw the South London stone in Yantlet Creek. Sunset when we reached Grain, saw Grain Tower Battery. Rolled up to Rochester station in the dark. Pizzas and beers for the train ride home. That rare thing with coastal adventures - a single day ride.

## `r rides$details[rides$activity_id == 6184233328]`

Night before in Chester with a big curry. Expected a damp one. Briefly cut into Wales (though that first section didn’t actually count to the adventure). Very windy as we approached the Mersey. No ferries running, and not allowed in the road tunnels, so we had to get a train for the hop across (under) the river. All went to shit when we came out of the train station - big hail storm, then I punctured, then Wendy broke his cleat (had spotted the night before on the train one cleat was looking very thin). Thankfully still in Liverpool so a quick run to the Giant store later we we good to go again. Brutal weather as we pushed out of Liverpool, but the sun came out when we got to Lytham. Schalk knee pain when we hit Blackpool, so diversion to pharmacy. At this point knew we wouldn’t make the ferry at Fleetwood so had to cut inland. Used google maps directions via headphones and it sent us down a track that got wilder and wilder. Until it was knee deep puddles and mud. In the dark. Made it through to Lancaster in the end. Absolute legends at the pub we were staying in - we were too late to eat, but they let us get takeaway ordered, and let us keep our bikes in the bar overnight. Beer tasted amazing too.

## `r rides$details[rides$activity_id == 6188924719]`

Started the day in the pissing rain. Not a good omen! Had to call a halt in Morecambe to get coffee and dry out a bit. Then round the corner to the pound shop to buy Marigolds - gloves already soaked through. We were heading towards Sellafield and were stopped at a level crossing as the nuclear train came through. Lots of flooding about, including one lane that was like a river. No obvious detour options so tired to ride down it. Once we got past BB depth had to pack it in and climb into a flooded golf course and walk our way out. Crash with Wyndy - a van coming towards squeezed us to the side of the road. There was a pot hole under water which I hit and crashed with Wyndy crashing into me. Beautiful scenery once past Barrow-in-Furness with things getting noticeably wilder. Then Schalk snapped his cleat just as Wyndy had the day before.
Stayed the night in Seascale with that absolute dickhead of an owner. Too late for dinner so did chips and bread. But did it immediately and as soon as we got down from showering said it was cold and he’d thrown it away. Had a massive go at Wyndy. Twat.

## `r rides$details[rides$activity_id == 6193006840]`

Woke up to pissing rain again. Loaded up our bikes in the dry of the shed and  were very reluctant to head out! Strapped Schalk’s foot to the pedal with a Voile Strap. Very blustery on the run along the coast and clifftops to Workington where we went to McDonalds for the best deserved breakfast ever. Stopped in Silloth at the Fairydust Emporium - the most unique cafe experience ever. Absolutely charming people just when cold wet cyclists needed it! Weather slowly improved as we made our way up Solway Firth with a beautiful double rainbow in Bowness. Arrived at Carlisle in time for our booked train back to London and then the fun really began.
Trains were in a mess as the heavy rainfall had created flooding on the line, leading to numerous cancellations. Added to this, it was COP26 in Glasgow that weekend which meant the trains were extra busy. Chances of bike spaces for three was nil. Katie was super helpful at the station and kept texting Wyndy. In the end we had to get the family room at the local Travelodge for the night and get a train at the crack of dawn to London next day.

## `r rides$details[rides$activity_id == 7055062883]`

A short hop, with ride itself beginning in Glasgow after catching the morning train from London. Got the ferry over to Brodick on the Isle of Arran. Glorious hop down the coast to Whiting Bay for a beautiful evening on the beach and in the restaurant. 

## `r rides$details[rides$activity_id == 7060605792]`

Woke up to a stunning day, best view from a hotel window for the whole coastal project? Possibly one of the best days of riding too. Started with an almost complete lap of Arran, round to the ferry terminal at Lochranza. Great little cafe there, clear blue water on the ferry ramp, and sheep relaxing in the spots where cars are meant to queue. Took ferry to Claonaig and then rode down Kintyre to Campbeltown before riding back up the western side of the peninsula to Tarbert for the night. 

## `r rides$details[rides$activity_id == 7066002617]`

From one of the best days to one of the very toughest. There was an ominous red sky as the day dawned and we headed off. The route was isolated - I had extra water strapped on the fork as we would be hours before the first shop. Limited tarmac options for staying near the coast so we had to take a few gravel tracks to join the dead end paved roads together. Elsey Estate the first of these. Stopped once we were off the estate to eat the hard boiled eggs Schalk had made in the kettle. Rain had been drizzling all morning, but started to pick up at this point. Stopped for lunch at Craobh Haven and took the opportunity to get some dry kit on. We were only 27 miles from Oban and feeling pleased that a difficult day was nearly done. 
The other major bit of gravel took us over Bealach na Gaoithe (the 'pass of the winds'). A steep loose climb up with fog and howling wind on the top. Waited for Wyndy, and as we rolled on, he flatted. Too big a cut for tubeless to seal, so had to get a tube in there. He’d put his tubes right at the bottom of his bag so bad to unpack everything right there on the hill. We were all get seriously cold and needed to get riding asap. There was a tricky descent with lots of sharp stones on the other side which we negotiated very carefully, terrified of another puncture. A couple of miles later we hit tarmac again and with the rain lashing down absolutely hammered it to  Oban desperate to get warm. Airbnb had a dryer and apart from a quick Tennants at the pub, and grabbing a takeaway curry, spent the night in recovering and getting our kit ready for Mull the next day. Wyndy melted his helmet on a radiator.

## `r rides$details[rides$activity_id == 7072272567]`

Breakfast by Oban harbour at Wetherspoons. Ferry ride to Mull. Goosebump inducing ride round the western side of the  island. It was a Sunday so the ferry service was limited. We got the first boat from Oban to Craignure and had 5 hours to make it Tobermory. There’s a quick route on the eastern edge, but we wanted to take the longer more remote option. Again no shops etc so had to carry everything we needed. Did ok on timings but had to put a proper squeeze on the last hour. Got to Tobermory to find there’d been an issue with the ferries and most cancelled. Luckily there was one running we were able to get. Got the ferry ok to Kilchoan (check spelling)  and then rode on to Acharacle where we were spending the night in a lovely hotel. Dinner of venison, and a bit too much whisky playing darts with the locals in the bar. 

## `r rides$details[rides$activity_id == 7076591578]`

Sore heads next morning, so luckily the shortest ride of this trip. Wound our way along the coast to Mallaig for the ferry over to (where??) on the Isle of Skye. Found the most amazing spot for a beer a few miles on (find location), and rode through that incredible isolated heathland to Harrapool. Amazing dinner at the pub up the road. 

## `r rides$details[rides$activity_id == 7081454837]`

Crossed the bridge back to the mainland at the Kyle of Lochalsh. Breakfast in a cafe immediately after the bridge. At the turn off where our ride joined what would be the NC500 route we turned east to head towards Inverness and our sleeper train home. Though this section of the ride wasn’t  contributing to our coastal miles, it was a beautiful trip through the highlands. 

## `r rides$details[rides$activity_id == 7403080498]`

The first dedicated island trip. The very enjoyable opportunity as well to do it on road bikes and without any luggage. Went anti-clockwise round and had to contend with a very stiff SW wind. Otherwise a beautiful day. 

## `r rides$details[rides$activity_id == 7709542211]`

Taking the opportunity of a bank holiday in Whitstable, rode to Rochester to pick up where we’d left off with our exploration of the Thames estuary. After following the River Medway out of Rochester, did a lap of Sheppey. The return leg, across Harty Marshes, was lovely. 

## `r rides$details[rides$activity_id == 7742970954]`

Murray’s first trip started with an evening train to Carlisle. We ended up staying in the exact same family room we’d taken refuge in the night the trains were all cancelled. Breakfast at Wetherspoons and we were off. A short hop to Gretna where we crossed the border into Scotland. Beautiful clear day as we rolled along the north side of Solway Firth. Stopped for a coffee at that nice place by the river (find location) to enjoy the sunny weather that, sadly, wasn’t going to last. Clouds were gather as we arrived at our hotel in Newton Stewart. The rain began to hammer down in the early hours. 

## `r rides$details[rides$activity_id == 7749140338]`

Over breakfast next morning, we knew a tough day was ahead. Rolled out in pissing rain, but at least it wasn’t too cold. Coffee at the Isle of Whithorn. Lunch in Stranraer at Papa Rab’s for huge pasta dishes and some changes of clothing. The the rain really picked up again. A faint view of Alisa Craig through the mist. Absolutely swam into Ayr and our hotel, where the owner was not very happy about wet cyclists turning up. 

## `r rides$details[rides$activity_id == 7753830579]`

The day started damp, but not as bad as the evening before. Rolled out of Ayr heading north up the coast. After an hour or so I stacked it on a roundabout (where?) and took Schalk down too. No major injuries but both had decent cuts on left knees. The weather improving all the time, we road through Ardrossan where we’d caught the ferry to Arran six months earlier. We looked wistfully over at the island, remembering the incredible adventure we’d had earlier that year. Stopped for a spot of lunch at a nice place that also gave us some first aid supplies so we could get patched up. We carried on north, following the (name of body of water) as it became the River Clyde, then on to Glasgow for the train home. 

## `r rides$details[rides$activity_id == 8848979854]`

A very early morning train out of Waterloo (0544!) to Havant. Rode onto Hayling Island to be in time for the very first ferry of the day, but that meant a little bit of waiting. Thankfully sun was out so it wasn’t too cold. Rode round Portsmouth to our next ferry over to Gosport. After Gosport we took on a couple of gravel trails on our way to Warsash for ferry number 3 to Hamble. A bacon sarnie and a cup of tea later we were ready for the longest leg of the day. We rode northwest to make our way round Southampton Water and back down the other side. Absolutely stunning scenery on the Exbury Estate and round the Beaulieu river. After Lymington we took on Keyhaven Marshes, the clear views across the Solent to the Needles offsetting the now brisk headwind. We pushed on to Mudeford to catch the ferry across Christchurch harbour before they stopped running for the day. Making it with a bit of time to spare, we then cruised along the seafront to Bournemouth with just enough time spare to grab some beers before our train. 

## `r rides$details[rides$activity_id == 8972919601]`

Started the day with Schalk’s mechanical issues, sawing the end off his handlebars with a bread knife. Hammered round the portway to make up some time before crossing the bridge over the Severn. Industrial south wales was flat and featureless, so we used the opportunity to have a big day, pushing on for 125 miles knowing we had a lot of elevation to come. 

## `r rides$details[rides$activity_id == 8978887674]`

A flattish 60 miles to start the day but some real time pressure to catch the ferry from Ferryside to Llansteffan. That ferry operates in a narrow window either side of high water, and missing it means a further 16 miles to ride with plenty of additional climbing. Made it with about 10 mins to spare. Surreal standing of the expanse of sand at Ferryside with the mist rolling in as the amphibious ferry drove up the beach to collect us. Lunch in Llansteffan and then the climbing began. Rolled in to Tenby on a beautiful sunny afternoon for beers on the grass overlooking the sea. 

## `r rides$details[rides$activity_id == 8985824154]`

It rained hard overnight. Though it stopped as we were leaving, the clouds were so low we got soaked riding through. Soggy first part to Pembroke where Schalk got that train back to London - he’d been struggling with a hamstring injury. The right decision. Left Pembroke feeling low, rain had started again and we’d lost SB. Missed a lot of the Pembrokeshire coastal highlights as the mist was so bad we couldn’t see the sea. As it burned off we were treated to some stunning vistas. Left the route at Newport to climb up to a beautiful little village to stay in the pub there.

## `r rides$details[rides$activity_id == 8992413973]`

Tom Skipp’s birthday. Heavily front loaded climbing day with nearly 1500m in the first 30 miles. Very slow going initially as a result. After Aberystwyth climbed up the last proper hill overlooking Borth. Murray and Wyndy already there, Murray just chilling on the grass. Cruised down the hill, through Borth and then on the flat. Began to head away from the coast as far as Machynlleth where we left the coastal route proper and headed into the mountains for the Buckley Arms Chinese pub.

## `r rides$details[rides$activity_id == 9628132541]`

Train to Diss and the straight to the coast to join the route at Southwold. Pints at the Lord Nelson with Tom’s sister. Then hilarious slightly pissed gravel smash across the marshes. Running across the shingle when we couldn’t ride anymore at Minsmere. Following gravel tracks past the front of Sizewell nuclear power station before rolling into Aldeburgh for the night. 

## `r rides$details[rides$activity_id == 9634786328]`

Round the River Alde to Orford via the Sailor’s Path. From Orford on the gravel to Butley Ferry, the UK’s smallest. A row boat that could only take two people + two bikes. Two trips needed to get us across. Pushed on from there to Bawdsey for the ferry across the River Deben to Felixstowe Ferry. Lunch in Felixstowe then down to Languard Point for the ferry across the Orwell to Harwich. Tracing the edge of Dovercourt bay we felt the strength of the headwind for the first time. A quick detour to the Naze tower, then a long push into the headwind as we hugged to coastline down through Clacton and beyond; particularly tough once we were riding on top of the sea defences. Brief respite when we turned for Point Clear and the ferry across the River Colne to East Mersea. Round through West Mersea and across the Stroud to the mainland once more. Final effort on to Maldon and a very well deserved night’s rest. 

## `r rides$details[rides$activity_id == 9641255722]`

Rolled out of Maldon after a guesthouse breakfast for a lap of the Dengie peninsula. Very exposed to the wind and a brisk SW wind made it heavy going. Into Burnham-on-Crouch for a ferry hop across to Wallasea Island. Then just another 5 miles or so to Rochford where the coastal miles ended.

## `r rides$details[rides$activity_id == 11605843542]`

Started the day from the Buckley Arms (chinese hunting lodge) where we stayed the year before having ridden out from Chester the day before. Rolled down the valley to Machynlleth where we met Tom Skipp who had driven out from Bristol to Aberystwyth and then ridden up to meet us.
Slightly overcast to begin with but went through some beautiful little coastal towns like Aberdyfi. Barmouth was beautiful, crossing the wooden boarded cycle path over the estuary alongside the train track. Had stop for beers in Pwllheli. The on to Nefyn and the delightful pub for great beers and a kebab from the shop down the road. 

## `r rides$details[rides$activity_id == 11614847759]`

Early start for the biggest day of this trip. Very overcast and a bit of rain on and off all day, but not really enough to get properly wet.
Caernafon Castle and McDonald's breakfast. Then on to Anglesey for a photo opportunity with the long name train station. Then winding our way all the way round Aglesey itself - battling a vicious headwind all the way out to Holyhead. Dinner in the Owain Glendwr (spelling) pub just as the heavens opened. Then dashed out when the rain stopped briefly for the short hop to our airbnb in the middle of nowhere.

## `r rides$details[rides$activity_id == 11622261830]`

Sun was out again for what promised to be the easy day of the trip. Beautiful view alongside the Menai Strait and then over the Menai Bridge. Coffee in Bangor. Then on to Llandudno and round the Great Orne - utterly stunning views and riding round there.
Then a pan flat cruise along the coast paths in the sun. An idyllic way to round out the trip... until Schalk crashed. Double break of right radius, 5 broken ribs, fractured clavicle. Surgery to pin the arm and 4 nights total in hospital. And now we have to go back to Wales.

## `r rides$details[rides$activity_id == 14294527868]`

Train to Grantham day before to get to the route. Stayed the night in Boston. Then a heavy day skirting the marshes. Grass covered sea banks brutal to ride on - heavily rutted and the grass providing a lot of drag. Sutton Bridge for lunch with Uncle Colin. Last marsh stretch very hard work - herds of cows to negotiate. Weird houseboats - KLWNWA. Wildfowl hunting of some kind?
Then a very pleasant run in down the coast from snettisham to hunstanton. Inland route back to Kings Lynn for train home.

## `r rides$details[rides$activity_id == 15095197221]`

Really hot day (30+ degrees). Train down in the afternoon in order to get a night ride back to London (TS training for TPR). Slow going for the coastal section with plenty of gravel. Itchenor ferry, pissed Dean by the ferry borrowing TS phone to call his mum because he’d fallen out of his kayak and lost his phone. Amazing section riding along the beach. Beautiful paths around the marshes. Finished the coastal section in Ferring with an amazing kebab and then a long ride through the night with plenty of gravel to get back to London, arriving home just before 0300.

## `r rides$details[rides$activity_id == 15709407056]`

Challenges even getting to start point. Meant to get night train to Inverness Wednesday night, ride through the Great Glen to Oban on Thursday, and catch ferry to Barra on Friday. Night train cancelled last minute, so spent the night on the train in Euston station before taking a train next morning to Glasgow and riding to Oban from there. Despite the delays that meant in getting started, had an amazing ride through the Trossachs and got into Oban that evening and hence back on our schedule. 
Had a bumpy crossing on the ferry to Castlebay with very strong southerly winds expected over the next few days. As soon as we were off the ferry (about 1800 that evening) we rode as far south as we could in Vatersay - snapping a pic overlooking an absolutely stunning beach - before turning north to ride to the very top of Barra and get our coastal miles ticked off. We flew north with the wind now behind us, stopping at a small house that did a sideline in pizzas (thank god we booked ahead, remember that gleeful guy who told us we were too late as we arrived). Ate these by the side of the road as it started raining before heading off to the working Croft we were staying on (remember Archie!). Dumped bags and carried on north as twilight fell. Rode passed Barra airport, deserted with the tide covering its runways, and carried on to the northernmost point. Coastal miles in the bag, we then turned back south and to Archie’s. We now had a block headwind to contend with but 45 mins hard work saw us home. Put our bikes in the barn which was absolutely packed with starlings (Archie: “as you’ll see, we’ve got a wee starling problem”)

## `r rides$details[rides$activity_id == 15720148185]`

Up early the next morning to catch the first ferry of the day to Eriskay. Very surreal in the barn that morning, strapping bags to our bikes in the dark with an absolute cacophony coming from the hundreds of starlings perched in the beams that we had disturbed. Rode off in the dark, first light as we approached Ardmhòr and the ferry. 
Uneventful ferry crossing save for a pleasant sunrise and on to Eriskay. Had plenty of miles to cover to ensure we made the last ferry of the day to Harris. Rode north through South Uist, absolutely flying along with that strong wind behind us. Rode through the military firing range before stoping at the Hebridean Jewellers that was also a café. The Uists, Benbecula, etc very flat, sweeping beaches, marsh grass etc. Causeway after causeway as we linked island to island. Tough section at the top of North Uist as we turned east - very strong crosswind and horizontal rain made for heavy going. 
Then it was on to the ferry to Harris. Could see as we crossed the Sound of Harris that the landscape was about to change with the mountains ahead of us a stark contrast with the flat land behind. 
First stop on Harris was at the community shop to load up on supplies for the next day. We would be riding through Lewis on a Sunday which, with the strict sabbath observance on the islands, meant we wouldn’t be able to pick up and food or water. 
Then about 20 miles on to our guest house on the outskirts of Tarbert. Breathtaking scenery and beautiful beaches. One decent climb to overcome and then descending all the way to our stop for the night. Rode into Tarbert for our dinner. 

## `r rides$details[rides$activity_id == 15731925300]`

A day without ferries, so a slightly more relaxed start to the morning. Once again enjoying the stunning scenery as we made our way north, tackling another decent climb early on as we crossed the mountain range separating Harris from Lewis. Long plod north, seemingly never quite having the wind in a favourable direction for long. Stopped at that shieling, tempting to stay a while!

Pushed on to the Butt of Lewis. Caught up with loads of other cyclists there who had clearly been doing the Hebridean Way, but on a more leisurely schedule- actually taking the time soak it up. From there we had the run to Stornoway - back into the wind. Wasn’t too bad as we rode down the west coast of Lewis, but as soon as we turned for Stornoway the 11 miles across the moor were seriously heavy going. We were now smack into the wind, and the rain clouds that had been gathering ominously let loose. It was suddenly very dark, with car headlights coming over the brow of a far off hill showed us quite how long the upward drag would continue. We pressed on instead of grabbing rain gear - we weren’t far from the finish after all - but were soon soaked through. Plenty warm with the hard work, but the thought of a mechanical and roadside stop was suddenly terrifying. Still, made it there fine and had a very pleasant dinner at the snazziest place in town. 
Next morning we were up early for the morning ferry to Ullapool. Delayed arrival with the coastguard helicopter having to attend and lift off a medical emergency. That aside, a beautiful ride to Inverness across the highlands and the night train home. 

## `r rides$details[rides$activity_id == 19088138409]`
What started as an idea to get some climbing in ahead of a trip to the mountains to watch the Tour de France became a plan to ride through some big welsh hills to the coast and tick off the small section of coastline left unridden following Schalk’s big crash. 
Very early start out of Euston to get the train to Chester. Lovely day through the hills and on to the coast. My rear derailleur failed and left me spinning in high cadence for half the ride. Picked up the route shortly before the crash site and then an uneventful ride along the coast back to Chester for the train home.
